version: '3.9'

services:

  db:
    container_name: db
    image: postgres:14
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpswrd
      - POSTGRES_DB=test_db

  web:
    container_name: web_app
    build: ./web_app
    networks:
      - backend
    command: sh ./run.sh
    volumes:
      - static_volume:/usr/src/web_app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - backend
    ports:
      - '1488:80'
    volumes:
      - static_volume:/usr/src/web_app/staticfiles/
    depends_on:
      - web

networks:
  backend:

volumes:
  postgres_data:
  static_volume:
