version: '3.9'

services:

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpswrd
      - POSTGRES_DB=test_db

  web:
    build: ./web_app
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/web_app/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


  nginx:
    build: ./nginx
    ports:
      - '1488:80'
    volumes:
      - static_volume:/usr/src/web_app/staticfiles/
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
